### ISSUE TITLE
infografica-carlos gatica osorio

### ISSUE THREAD

**Issue by carlos0716c** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-carlos0716c#1]
[typescript.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-carlos0716c/files/15226848/typescript.pdf)

**Comment by Nelsy21** [comment]
calificado conforme a la rubrica 
18/20

**Comment by josealfredo79** [comment]
Revisado...
